In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[1.7753e+28, 2.8297e+32, 2.6617e+23],
        [1.8615e+25, 2.8942e+12, 7.5338e+28],
        [7.1758e+22, 1.4603e-19, 6.8801e+16],
        [1.8370e+25, 1.4348e-19, 2.7530e+12],
        [7.5338e+28, 1.5975e-43, 0.0000e+00]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3000, 0.0705, 0.3866],
        [0.9069, 0.7332, 0.1131],
        [0.1483, 0.9055, 0.9752],
        [0.5237, 0.1633, 0.8662],
        [0.9185, 0.8832, 0.6155]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.6686, -1.0543,  2.7749],
        [ 2.4957,  0.4188,  1.1773],
        [-0.7490,  0.5152, -0.0066],
        [ 0.7327, -0.1656,  0.2432],
        [ 2.0401,  1.8033, -0.8932]])


In [7]:
print(x.size())

torch.Size([5, 3])


In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.5461, -0.5791,  3.4913],
        [ 3.3763,  0.9910,  1.1862],
        [ 0.0102,  0.6064,  0.0172],
        [ 1.4320,  0.7107,  0.9392],
        [ 2.7146,  2.7637, -0.4089]])


In [9]:
print(torch.add(x, y))

tensor([[ 1.5461, -0.5791,  3.4913],
        [ 3.3763,  0.9910,  1.1862],
        [ 0.0102,  0.6064,  0.0172],
        [ 1.4320,  0.7107,  0.9392],
        [ 2.7146,  2.7637, -0.4089]])


In [11]:
result = torch.empty(5, 3)
torch.add(x, y , out=result)
print(result)

tensor([[ 1.5461, -0.5791,  3.4913],
        [ 3.3763,  0.9910,  1.1862],
        [ 0.0102,  0.6064,  0.0172],
        [ 1.4320,  0.7107,  0.9392],
        [ 2.7146,  2.7637, -0.4089]])


In [12]:
y.add_(x)
print(y)

tensor([[ 1.5461, -0.5791,  3.4913],
        [ 3.3763,  0.9910,  1.1862],
        [ 0.0102,  0.6064,  0.0172],
        [ 1.4320,  0.7107,  0.9392],
        [ 2.7146,  2.7637, -0.4089]])


In [13]:
print(x[:, 1])

tensor([-1.0543,  0.4188,  0.5152, -0.1656,  1.8033])


In [14]:
x = torch.rand(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [15]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.5221])
-0.522064208984375


In [16]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [17]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [18]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [19]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [20]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([0.4779], device='cuda:0')
tensor([0.4779], dtype=torch.float64)
